// SPDX-License-Identifier: LGPL-3.0-or-later
import http from 'node:http';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { env, pipeline, InterruptableStoppingCriteria, TextStreamer } from '@huggingface/transformers';
import { readModelRequestBody } from './model-request-body.mjs';
import { checkedMessages, checkedTools, decodeGeneratedTools } from './generation-tools.mjs';
import { completionStream } from './generation-stream.mjs';

export const LOCAL_GENERATION_MODEL = 'HuggingFaceTB/SmolLM2-135M-Instruct';
export const LOCAL_GENERATION_REVISION = '12fd25f77366fa6b3b4b768ec3050bf629380bac';
export const LOCAL_GENERATION_MODELS = Object.freeze({
  [LOCAL_GENERATION_MODEL]: { revision: LOCAL_GENERATION_REVISION, dtype: 'q4' },
  'onnx-community/Qwen2.5-0.5B-Instruct': { revision: 'cc5cc01a65cc3ff17bdb73a7de33d879f62599b0', dtype: 'q4' },
  'onnx-community/Qwen2.5-1.5B-Instruct': { revision: '6287331f475a3e20e8c879be8fd4bf3551ad9d34', dtype: 'q4' },
});

/** Accept the single translation envelope supported by the local text transport. */
function translationWrapper(format) {
  if (format === undefined) return false;
  const schema = format?.json_schema?.schema;
  if (!format || typeof format !== 'object' || Array.isArray(format)
      || format.type !== 'json_schema' || schema?.type !== 'object'
      || Object.keys(schema).some(key => !['type', 'additionalProperties', 'required', 'properties'].includes(key))
      || schema.additionalProperties !== false
      || JSON.stringify(schema.required) !== '["translated_text"]'
      || JSON.stringify(Object.keys(schema.properties || {})) !== '["translated_text"]'
      || schema.properties.translated_text?.type !== 'string'
      || Object.keys(schema.properties.translated_text).some(key => !['type', 'minLength'].includes(key))
      || schema.properties.translated_text?.minLength !== 1) {
    throw new RangeError('unsupported_response_format');
  }
  // The transport encodes real generated bytes. The model does not enforce JSON.
  return true;
}

/** Validate chat input and cap generation at the configured local token budget. */
function checkedRequest(body, model, maxNewTokens) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) throw new RangeError('invalid_input');
  if (body.model !== model) throw new RangeError('unknown_model');
  if (Object.hasOwn(body, 'stream') && typeof body.stream !== 'boolean') {
    throw new RangeError('unsupported_tools_or_stream');
  }
  const selection = checkedTools(body, model.startsWith('onnx-community/Qwen2.5-'));
  const messages = checkedMessages(body.messages);
  if (body.max_tokens !== undefined && body.max_completion_tokens !== undefined
      && body.max_tokens !== body.max_completion_tokens) throw new RangeError('invalid_max_tokens');
  const requestedTokens = body.max_completion_tokens ?? body.max_tokens ?? maxNewTokens;
  if (!Number.isInteger(requestedTokens) || requestedTokens < 1 || requestedTokens > 4096) throw new RangeError('invalid_max_tokens');
  if (body.stream_options !== undefined && (!body.stream_options || typeof body.stream_options !== 'object'
      || Array.isArray(body.stream_options) || Object.keys(body.stream_options).some(key => key !== 'include_usage')
      || typeof body.stream_options.include_usage !== 'boolean')) throw new RangeError('unsupported_stream_options');
  const wrapped = translationWrapper(body.response_format);
  if (wrapped && selection.tools.length) throw new RangeError('unsupported_response_format');
  return { messages, selection, maxTokens: Math.min(requestedTokens, maxNewTokens), wrapped,
    stream: body.stream === true, includeUsage: body.stream_options?.include_usage === true };
}

/** Decode actual local model tokens while preserving EOS versus token-limit completion. */
async function generate(generator, input, stoppingCriteria, onText) {
  const templated = generator.tokenizer.apply_chat_template(input.messages, {
    tokenize: false, add_generation_prompt: true, tools: input.selection.tools.length ? input.selection.tools : null,
  });
  const encoded = generator.tokenizer(templated, { add_special_tokens: false, padding: false, truncation: false });
  const promptTokens = encoded.input_ids.dims.at(-1);
  if (promptTokens + input.maxTokens > 8192) throw new RangeError('context_window_exceeded');
  const streamer = onText ? new TextStreamer(generator.tokenizer, { skip_prompt: true, callback_function: onText }) : undefined;
  const output = await generator.model.generate({ ...encoded, max_new_tokens: input.maxTokens, do_sample: false,
    stopping_criteria: stoppingCriteria, ...(streamer ? { streamer } : {}) });
  const tokens = output.tolist()[0].slice(promptTokens);
  const content = generator.tokenizer.decode(tokens, { skip_special_tokens: true });
  const configuredEos = generator.model.generation_config?.eos_token_id ?? generator.model.config.eos_token_id;
  const eosIds = (Array.isArray(configuredEos) ? configuredEos : [configuredEos]).map(Number);
  const stopped = eosIds.includes(Number(tokens.at(-1)));
  if (!content.trim()) throw new RangeError('empty_generation');
  return { content, finishReason: stopped ? 'stop' : 'length', promptTokens, completionTokens: tokens.length };
}

/** Start an offline loopback service with native text streaming and validated generated tool calls. */
export async function startGenerationServer({
  port = 0,
  cacheDir = process.env.FORESIGHT_MODEL_CACHE || fileURLToPath(new URL('../.cache/models/', import.meta.url)),
  model = process.env.FORESIGHT_GENERATION_MODEL || LOCAL_GENERATION_MODEL,
  maxNewTokens = 512,
  timeoutMs = 180000,
  requestTimeoutMs = 10000,
} = {}) {
  const descriptor = Object.hasOwn(LOCAL_GENERATION_MODELS, model) && LOCAL_GENERATION_MODELS[model];
  if (!descriptor) throw new RangeError('Only pinned local generation models are supported');
  if (!Number.isInteger(maxNewTokens) || maxNewTokens < 1 || maxNewTokens > 1024) throw new RangeError('maxNewTokens must be 1..1024');
  if (!Number.isInteger(timeoutMs) || timeoutMs < 1 || timeoutMs > 180000) throw new RangeError('timeoutMs must be 1..180000');
  if (!Number.isInteger(requestTimeoutMs) || requestTimeoutMs < 1 || requestTimeoutMs > 30000) throw new RangeError('requestTimeoutMs must be 1..30000');
  env.cacheDir = cacheDir;
  env.allowLocalModels = true;
  env.allowRemoteModels = false;
  const generator = await pipeline('text-generation', model, {
    ...descriptor, device: 'cpu',
    session_options: { intraOpNumThreads: 2, interOpNumThreads: 1 },
  });
  let active = false;
  const server = http.createServer(async (request, response) => {
    const reply = (status, body) => {
      if (response.destroyed || response.writableEnded) return;
      response.writeHead(status, { 'content-type': 'application/json' });
      response.end(JSON.stringify(body));
    };
    let timer;
    let stoppingCriteria;
    let ownsInference = false;
    let timedOut = false;
    let wire;
    try {
      if (request.method === 'GET' && request.url === '/health') return reply(200, { status: 'ok', model, provider: 'transformers-js', offline: true, busy: active });
      if (request.method === 'GET' && request.url === '/v1/models') return reply(200, { object: 'list', data: [{ id: model, object: 'model', owned_by: 'local' }] });
      if (request.method !== 'POST' || !['/v1/chat/completions', '/chat/completions'].includes(request.url)) return reply(404, { error: 'route_not_found' });
      const bytes = await readModelRequestBody(request, response, requestTimeoutMs);
      if (bytes === null) return;
      const input = checkedRequest(JSON.parse(bytes.toString('utf8')), model, maxNewTokens);
      if (active) return reply(429, { error: 'generation_busy' });
      active = ownsInference = true;
      stoppingCriteria = new InterruptableStoppingCriteria();
      timer = setTimeout(() => { timedOut = true; stoppingCriteria.interrupt(); }, timeoutMs);
      response.once('close', () => { if (!response.writableEnded) stoppingCriteria.interrupt(); });
      const metadata = { id: `chatcmpl-${randomUUID()}`, created: Math.floor(Date.now() / 1000), model };
      wire = input.stream ? completionStream(response, metadata) : null;
      let streamed = '';
      let openedText = false;
      const onText = input.stream && !input.selection.tools.length ? text => {
        if (timedOut || response.destroyed) return;
        if (!openedText) {
          wire.delta({ role: 'assistant', content: input.wrapped ? '{"translated_text":"' : '' });
          openedText = true;
        }
        streamed += text;
        wire.delta({ content: input.wrapped ? JSON.stringify(text).slice(1, -1) : text });
      } : undefined;
      const generated = await generate(generator, input, stoppingCriteria, onText);
      if (timedOut) return response.headersSent ? wire.fail('generation_timeout') : reply(504, { error: 'generation_timeout' });
      if (onText && streamed !== generated.content) throw new Error('generation_stream_decode_mismatch');
      const parsed = input.selection.tools.length ? decodeGeneratedTools(generated.content, generated.finishReason, input.selection)
        : { content: generated.content, finishReason: generated.finishReason };
      const message = { role: 'assistant', content: input.wrapped ? JSON.stringify({ translated_text: generated.content }) : parsed.content,
        ...(parsed.tool_calls ? { tool_calls: parsed.tool_calls } : {}) };
      const usage = { prompt_tokens: generated.promptTokens, completion_tokens: generated.completionTokens,
        total_tokens: generated.promptTokens + generated.completionTokens };
      const provenance = { provider: 'transformers-js', ...descriptor, device: 'cpu', offline: true, max_new_tokens: input.maxTokens,
        structured_output: input.wrapped ? 'transport_wrapped_generated_text' : parsed.tool_calls ? 'validated_generated_tool_calls' : 'none',
        ...(parsed.tool_calls ? { raw_tool_output: generated.content } : {}) };
      if (wire) {
        if (openedText && input.wrapped) wire.delta({ content: '"}' });
        if (!openedText) wire.delta({ role: 'assistant', content: message.content || '' });
        for (const [index, call] of (parsed.tool_calls || []).entries()) wire.delta({ tool_calls: [{ index, ...call }] });
        wire.finish(parsed.finishReason, usage, provenance, input.includeUsage);
        return;
      }
      return reply(200, {
        ...metadata, object: 'chat.completion', choices: [{ index: 0, message, finish_reason: parsed.finishReason }],
        usage, local_generation: provenance,
      });
    } catch (error) {
      if (response.headersSent) { wire?.fail(timedOut ? 'generation_timeout' : 'generation_failed'); return; }
      if (timedOut) return reply(504, { error: 'generation_timeout' });
      return reply(error instanceof SyntaxError || error instanceof RangeError ? 400 : 500, {
        error: error instanceof SyntaxError ? 'invalid_json' : error instanceof RangeError ? error.message : 'generation_failed',
      });
    } finally {
      clearTimeout(timer);
      if (ownsInference) active = false;
    }
  });
  try {
    await new Promise((resolve, reject) => { server.once('error', reject); server.listen(port, '127.0.0.1', resolve); });
  } catch (error) {
    await generator.dispose();
    throw error;
  }
  return {
    server, model, baseUrl: `http://127.0.0.1:${server.address().port}/v1`,
    async close() { await new Promise((resolve, reject) => server.close(error => error ? reject(error) : resolve())); await generator.dispose(); },
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const service = await startGenerationServer({ port: Number(process.env.FORESIGHT_GENERATION_PORT || 11435) });
  console.log(JSON.stringify({ status: 'ready', baseUrl: service.baseUrl, model: service.model }));
  for (const signal of ['SIGINT', 'SIGTERM']) process.once(signal, async () => { await service.close(); process.exit(0); });
}
