// SPDX-License-Identifier: LGPL-3.0-or-later
import assert from 'node:assert/strict';
import {setImmediate as nextTurn} from 'node:timers/promises';
import {mock, test} from 'node:test';
import {TextStreamer} from '@huggingface/transformers';
import {LOCAL_GENERATION_MODEL, startGenerationServer} from './generation-server.mjs';

const prompt = 'Private marker 81db7c: count from 1 to 100, explaining each number in a short sentence.';

async function request(service, overrides = {}) {
  const response = await fetch(`${service.baseUrl}/chat/completions`, {
    method: 'POST', headers: {'content-type': 'application/json', authorization: 'Bearer private-test-credential'},
    body: JSON.stringify({model: service.model, max_tokens: 128,
      messages: [{role: 'user', content: prompt}], ...overrides}),
  });
  return {status: response.status, body: await response.json()};
}

test('real native inference exposes metadata progress and usage without request or generated content', async () => {
  const events = [];
  const service = await startGenerationServer({model: LOCAL_GENERATION_MODEL, maxNewTokens: 80,
    observer: event => events.push(event)});
  try {
    const result = await request(service);
    assert.equal(result.status, 200);
    assert.deepEqual(events.slice(0, 3).map(event => event.stage), ['admitted', 'prefill', 'first-token']);
    assert.deepEqual(events.slice(-2).map(event => event.stage), ['completed', 'settled']);
    const complete = events.at(-2);
    assert.equal(complete.promptTokens, result.body.usage.prompt_tokens);
    assert.equal(complete.generatedTokens, result.body.usage.completion_tokens);
    assert.equal(complete.totalTokens, result.body.usage.total_tokens);
    assert.equal(events.at(-1).outcome, 'completed');
    assert(events.some(event => event.stage === 'progress'), 'the actual long completion reaches a native progress checkpoint');
    const allowed = new Set(['stage', 'requestId', 'model', 'maxTokens', 'elapsedMs', 'promptTokens',
      'generatedTokens', 'totalTokens', 'finishReason', 'outcome', 'code']);
    for (const event of events) {
      assert(Object.isFrozen(event));
      assert(Object.keys(event).every(key => allowed.has(key)));
      assert.equal(event.model, service.model);
      assert.equal(event.maxTokens, 80);
      assert.match(event.requestId, /^[a-f0-9-]{36}$/);
      assert(Number.isFinite(event.elapsedMs) && event.elapsedMs >= 0);
    }
    assert.equal(new Set(events.map(event => event.requestId)).size, 1);
    const serialized = JSON.stringify(events);
    for (const secret of [prompt, '81db7c', 'private-test-credential', result.body.choices[0].message.content]) {
      assert(!serialized.includes(secret), 'observer data cannot contain private request or generated bytes');
    }
  } finally {
    await service.close();
  }
});

test('an observer cannot change deterministic native completion, even when its sink fails', async () => {
  const plain = await startGenerationServer({model: LOCAL_GENERATION_MODEL, maxNewTokens: 8});
  let baseline;
  try {
    baseline = await request(plain);
    assert.equal(baseline.status, 200);
  } finally { await plain.close(); }
  const reports = mock.method(console, 'error', () => {});
  const service = await startGenerationServer({model: LOCAL_GENERATION_MODEL, maxNewTokens: 8,
    observer: event => {
      if (event.stage === 'prefill') throw new Error('private synchronous sink failure');
      if (event.stage === 'first-token') return Promise.reject(new Error('private asynchronous sink failure'));
    }});
  try {
    const observed = await request(service);
    await nextTurn();
    assert.equal(observed.status, 200);
    assert.deepEqual(observed.body.choices, baseline.body.choices);
    assert.deepEqual(observed.body.usage, baseline.body.usage);
    assert.deepEqual(observed.body.local_generation, baseline.body.local_generation);
    assert.deepEqual(reports.mock.calls.map(call => call.arguments), [
      ['[generation-observer] observer_failed'], ['[generation-observer] observer_failed'],
    ]);
  } finally {
    await service.close();
    reports.mock.restore();
  }
});

test('actual native timeout records interruption separately from settlement', async () => {
  const events = [];
  const service = await startGenerationServer({model: LOCAL_GENERATION_MODEL, timeoutMs: 1,
    observer: event => events.push(event)});
  try {
    assert.deepEqual(await request(service), {status: 504, body: {error: 'generation_timeout'}});
    const interruption = events.find(event => event.stage === 'interruption-requested');
    assert.equal(interruption?.code, 'generation_timeout');
    assert.equal(events.at(-1).stage, 'settled');
    assert.equal(events.at(-1).outcome, 'interrupted');
    assert.equal(events.at(-1).code, 'generation_timeout');
    assert(events.at(-1).elapsedMs >= interruption.elapsedMs);
    assert(!events.some(event => event.stage === 'completed'));
  } finally { await service.close(); }
});

test('close joins real token generation and exposes one interrupted settlement', async () => {
  const events = [];
  let entered, nestedClose;
  const firstToken = new Promise(resolve => { entered = resolve; });
  const service = await startGenerationServer({model: LOCAL_GENERATION_MODEL,
    observer: event => {
      events.push(event);
      if (event.stage === 'first-token') entered();
      if (event.stage === 'interruption-requested') nestedClose = service.close();
    }});
  const result = request(service);
  try {
    await firstToken;
    const closing = service.close();
    assert.equal(nestedClose, closing, 'reentrant observer cleanup must share the existing close promise');
    await Promise.all([result, closing]);
    assert.equal(events.filter(event => event.stage === 'settled').length, 1);
    assert.equal(events.at(-1).outcome, 'interrupted');
    assert.equal(events.at(-1).code, 'generation_closing');
    assert(!events.some(event => event.stage === 'completed'));
  } finally {
    await service.close();
    await result;
  }
});

test('a failure after actual streamed model bytes exposes only a stable failure code', async () => {
  const events = [];
  const service = await startGenerationServer({model: LOCAL_GENERATION_MODEL,
    observer: event => events.push(event)});
  const original = TextStreamer.prototype.on_finalized_text;
  let actualText = false;
  const injection = mock.method(TextStreamer.prototype, 'on_finalized_text', function (text, end) {
    original.call(this, text, end);
    if (text.trim()) {
      actualText = true;
      throw new Error('private native failure marker 9237b4');
    }
  });
  try {
    const response = await fetch(`${service.baseUrl}/chat/completions`, {method: 'POST',
      headers: {'content-type': 'application/json'},
      body: JSON.stringify({model: service.model, max_tokens: 32, stream: true,
        messages: [{role: 'user', content: prompt}]}),
    });
    const body = await response.text();
    assert(actualText, 'the failure follows native generation, without substituting model output');
    assert(body.includes('generation_failed'));
    assert.equal(events.at(-1).stage, 'settled');
    assert.equal(events.at(-1).outcome, 'failed');
    assert.equal(events.at(-1).code, 'generation_failed');
    assert(!JSON.stringify(events).includes('9237b4'));
    assert(!JSON.stringify(events).includes(prompt));
    assert(!events.some(event => event.stage === 'completed'));
  } finally {
    injection.mock.restore();
    await service.close();
  }
});

test('a terminal transport failure cannot retain a completed settlement', async () => {
  const events = [];
  const service = await startGenerationServer({model: LOCAL_GENERATION_MODEL, maxNewTokens: 8,
    observer: event => events.push(event)});
  let refused = false;
  service.server.prependOnceListener('request', (_request, response) => {
    const original = response.end;
    response.end = function (data, ...args) {
      if (!refused && data === 'data: [DONE]\n\n') {
        refused = true;
        throw new Error('private terminal transport failure 473fe1');
      }
      return original.call(this, data, ...args);
    };
  });
  try {
    const response = await fetch(`${service.baseUrl}/chat/completions`, {method: 'POST',
      headers: {'content-type': 'application/json'},
      body: JSON.stringify({model: service.model, max_tokens: 8, stream: true,
        messages: [{role: 'user', content: prompt}]}),
    });
    assert((await response.text()).includes('generation_failed'));
    assert(refused);
    const completed = events.find(event => event.stage === 'completed');
    assert(completed.generatedTokens > 0, 'the actual model completed before the terminal write failed');
    assert.equal(events.at(-1).stage, 'settled');
    assert.equal(events.at(-1).outcome, 'failed');
    assert.equal(events.at(-1).code, 'generation_failed');
    assert(!JSON.stringify(events).includes('473fe1'));
  } finally { await service.close(); }
});
